# PostgreSQL configuration for RDS
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

production:
  <<: *default
  database: magi_archive_production
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>
  port: 5432

development: &development
  <<: *default
  database: magi_archive_development
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>
  port: 5432

test: &test
  <<: *default
  database: magi_archive_test
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>
  port: 5432

cucumber: *test
cypress: *test
profile: *development
